#!/usr/bin/env bash
# a script to print a story
lines=$(cat /etc/passwd)

while IFS= read -r ln; do
    # USERNAME=$($ln | cut -d ':' -f 1)
    # PASSWORD=$($ln | cut -d ':' -f 2)
    # USER_ID=$($ln | cut -d ':' -f 3)
    # GROUP_ID=$($ln | cut -d ':' -f 4)
    # USER_ID_INFO=$($ln | cut -d ':' -f 5)
    # HOME_DIRECTORY=$($ln | cut -d ':' -f 6)
    # COMMAND_SHELL=$($ln | cut -d ':' -f 7)
    echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $COMMAND_SHELL. $USER_ID's place is protected by the passcode $PASSWORD, more info about the user here: $USER_ID_INFO"
done <"$lines"
