#!/usr/bin/env bash
# a script to print "Best school" 10 times
i=1
while ((i <= 10)); do
    if ((i == 4)); then
        echo "bad luck"
    elif ((i == 8)); then
        echo "good luck"
    elif ((i == 4)); then
        echo "bad luck"
    else
        echo "Best School"
    fi
    ((i++))
done
