#!/usr/bin/env bash
# a script to print "Best school" 10 times
i=1
while ((i <= 20)); do
    echo $i
    if ((i == 4)); then
        echo "bad luck from China"
    elif ((i == 9)); then
        echo "bad luck from Japan"
    elif ((i == 17)); then
        echo "bad luck from Italy"
    else
        echo "Best School"
    fi
    ((i++))
done
