#!/usr/bin/env bash
# a script to print information about the school file
file="school"
if [ -f $file ]; then
    echo "school file exists"
    if [ -z "$(cat $file)" ]; then
    echo "school file is empty"
else
    echo "school file is not empty"
fi
else
    echo "school file does not exist"
fi


if [ -f $file ]; then
    echo "school is a regular file"
fi
