#!/usr/bin/env bash
# a script to print information about the school file
file="school"
if [ -e $file ]; then
    echo "school file exists"
else
    echo "school file does not exist"
fi

if [ -f $file ] && [ -z "$(cat $file)" ]; then
    echo "school file is empty"
else
    echo "school file is not empty"
fi

if [ -f $file ]; then
    echo "school is a regular file"
fi
