#!/usr/bin/env bash
# a script to to task 9
echo "$!" > /var/run/myscript.pid

# display message indefinitely
while true; do
    trap 'echo "I hate the kill command"; rm /var/run/myscript.pid; exit 0' SIGTERM
    trap 'echo "Y U no love me?!"' SIGINT   
    trap 'rm /var/run/myscript.pid; exit 0' SIGQUIT

    echo 'To infinity and beyond'
    sleep 2
done