#!/usr/bin/env bash
# a script to manage a process

if [ -z "$1" ]; then
    echo "Usage: manage_my_process {start|stop|restart}"
    exit 1
fi

case $1 in
    start)
        ./manage_my_process &
        echo "$!" > /var/run/my_process.pid
        echo "manage_my_process started";;
    stop)
        if [[ -f '/var/run/my_process.pid' ]]; then
            echo "Process not running"
            exit 1
        fi
        kill "$(cat /var/run/my_process.pid)" || { echo "Failed to stop process"; exit 1; }
        rm /var/run/my_process.pid
        echo "manage_my_process stopped";;
    restart)
        if [[ -f '/var/run/my_process.pid' ]]; then
            echo "Process not running"
            exit 1
        fi
        kill "$(cat /var/run/my_process.pid)" || { echo "Failed to stop process"; exit 1; }
        rm /var/run/my_process.pid
        ./manage_my_process &
        echo "$!" > /var/run/my_process.pid
        echo "manage_my_process restarted";;
    *)
        echo "Usage: manage_my_process {start|stop|restart}";;
esac